version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"

  server:
    build:
      context: .
    command: node server/server.js
    ports:
      - '5001:5001'
