version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:80"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: npm start
    ports:
      - '5001:5001'
